### ISSUE TITLE
RuntimeNullables breaks source link

### ISSUE THREAD

**Issue by Trojaner** [Singulink/RuntimeNullables#5]
Stepping into source code of libraries that use [source link](https://github.com/dotnet/sourcelink) and RuntimeNullables does not work.

![image](https://user-images.githubusercontent.com/1809172/107082239-f127b000-6804-11eb-8e01-21024c1730c5.png)

**Comment by mikernet** [comment]
Can you please elaborate with a complete description of the configuration and relationship between the various projects and packages?

**Comment by mikernet** [comment]
Is it something like this:
- `LibraryProject`: references `RuntimeNullables` and  `Source Link` nuget packages, creates a library nuget package
- `AppProject`: references `LibraryProject` nuget package and stepping into `LibraryProject` source no longer works here?

**Comment by Trojaner** [comment]
> Is it something like this:
> 
> * `LibraryProject`: references `RuntimeNullables` and  `Source Link` nuget packages, creates a library nuget package
> * `AppProject`: references `LibraryProject` nuget package and stepping into `LibraryProject` source no longer works here?

yes

**Comment by mikernet** [comment]
I'll have a look shortly and let you know. Thanks for the report!

**Comment by mikernet** [comment]
What are the target frameworks for the library and app projects?

**Comment by Trojaner** [comment]
net461 and netstandard2.0 for the library
net461 and netcoreapp3.1  for the app project

**Comment by mikernet** [comment]
Is that page coming up anytime you try to step into any source code at all or only when it attempts to break at an exception thrown by `RuntimeNullables`?

**Comment by mikernet** [comment]
Is the repo with the app where this is happening public so I can clone it and debug?

**Comment by Trojaner** [comment]
The repo is openmod/openmod. You can reference OpenMod.Core from an app project via NuGet (sources are in the framework folder). Keep in mind that you need to use the 3.0.0+ version.

**Comment by mikernet** [comment]
This was a tricky one. Closed via https://github.com/Singulink/RuntimeNullables/commit/7c91f336e81b567055d707680e5bc0e55b6eac95

Posting v0.9.8 to nuget now, give it a try and let me know if you have any more issues but it should be fixed.
