### ISSUE TITLE
InvalidProgramException when using C# 9 init only setters

### ISSUE THREAD

**Issue by fdipuma** [Singulink/RuntimeNullables#6]
Hey, very nice project :) it really helps out on filling the gap with nullable reference types.

There seems to be an issue with C# 9 init only properties on record types, any property setter (nullable or not) throws InvalidProgramException.

Stack trace:

```
System.InvalidProgramException
Common Language Runtime detected an invalid program.
   at Sample.Tests.Commands.CreateDocumentCommand.set_DocumentNumber(String value)
   at Sample.Tests.CreateDocumentCommandTests.Should_fail_create_command_when_duplicate_found() in D:\Dev\dotnet\Projects\nrttests\test\Sample.Tests\CreateDocumentCommandTests.cs:line 246
```

**Comment by mikernet** [comment]
Thanks for the report - I can reproduce the issue. Give me a bit here to see what I can do.

Note to self: modreq on the setter appears to confuse the return value void test, causing a nonsensical return value null test to be inserted.

**Comment by mikernet** [comment]
v1.0.0 is now available via NuGet, give 'er a go!

Closed by https://github.com/Singulink/RuntimeNullables/commit/bf08ee521c3fe0092b68e34debf5876efe08b60a

**Comment by fdipuma** [comment]
Wonderful! Works perfectly now, thanks 👍
